import express from 'express';
import cors from 'cors';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors({
  origin: '*', // For local development and remote deployments. Can be tightened later if needed.
  methods: ['GET', 'POST'],
  allowedHeaders: ['Content-Type']
}));
app.use(express.json());

// Health check endpoint
app.get('/health', (req, res) => {
  res.status(200).json({ status: 'OK', message: 'Server is running smoothly' });
});

// Contact endpoint
app.post('/api/contact', async (req, res) => {
  const { name, email, subject, message } = req.body;

  // Simple validations
  if (!name || !email || !message) {
    return res.status(400).json({
      success: false,
      message: 'Please fill in all required fields (Name, Email, and Message).'
    });
  }

  // Email format validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return res.status(400).json({
      success: false,
      message: 'Please enter a valid email address.'
    });
  }

  // Nodemailer transporter setup
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASS;
  const receiver = process.env.RECEIVER_EMAIL || user;

  if (!user || !pass) {
    console.error('SMTP credentials are missing in environment variables.');
    return res.status(500).json({
      success: false,
      message: 'Server mail configuration is incomplete. Please contact the administrator.'
    });
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: user,
      pass: pass
    }
  });

  // HTML Email Layout
  const htmlContent = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #f8fafc; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
      <h2 style="color: #8b5cf6; border-bottom: 2px solid #8b5cf6; padding-bottom: 12px; margin-top: 0; font-weight: 700; letter-spacing: -0.01em;">📬 New Contact Form Submission</h2>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr>
          <td style="padding: 10px 0; font-weight: 600; width: 120px; color: #475569; font-size: 14px;">Sender Name:</td>
          <td style="padding: 10px 0; color: #0f172a; font-size: 15px;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; font-weight: 600; color: #475569; font-size: 14px;">Sender Email:</td>
          <td style="padding: 10px 0; color: #0f172a; font-size: 15px;">
            <a href="mailto:${email}" style="color: #c084fc; text-decoration: none; font-weight: 500;">${email}</a>
          </td>
        </tr>
        <tr>
          <td style="padding: 10px 0; font-weight: 600; color: #475569; font-size: 14px;">Subject:</td>
          <td style="padding: 10px 0; color: #0f172a; font-size: 15px; font-style: italic;">${subject || 'No Subject Provided'}</td>
        </tr>
      </table>
      
      <div style="margin-top: 24px; padding: 18px; background-color: #ffffff; border-left: 4px solid #8b5cf6; border-radius: 6px; box-shadow: inset 0 2px 4px 0 rgba(0,0,0,0.02);">
        <p style="margin: 0; font-weight: 600; color: #475569; margin-bottom: 10px; font-size: 14px;">Message Details:</p>
        <p style="margin: 0; color: #334155; white-space: pre-wrap; line-height: 1.6; font-size: 15px;">${message}</p>
      </div>
      
      <div style="margin-top: 24px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px;">
        This email was automatically generated by your portfolio website contact form.
      </div>
    </div>
  `;

  const mailOptions = {
    from: `"Portfolio Contact" <${user}>`,
    to: receiver,
    replyTo: email,
    subject: `Portfolio Contact: ${subject || 'New Message from ' + name}`,
    text: `New Portfolio Message\n\nName: ${name}\nEmail: ${email}\nSubject: ${subject || 'N/A'}\n\nMessage:\n${message}`,
    html: htmlContent
  };

  try {
    await transporter.sendMail(mailOptions);
    return res.status(200).json({
      success: true,
      message: 'Message sent successfully! Prince will get back to you soon.'
    });
  } catch (error) {
    console.error('Error sending email via Nodemailer:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to send your message. Please try again later or contact directly.'
    });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
